
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<style>
body {
    font-family: DejaVu Sans;
    margin: 40, 10, 40, 10 px;

}

/* HEADER */
.header {
    text-align: center;
    margin-bottom: 10px;
    margin-top:10px;
}

.header h2 {
    margin: 0;
}
.header h5 {
    margin: 5px 0;
}

.header h6 {
    margin: 5px 0;
}
.header h7 {
    margin: 0;
    font-weight: normal;
    color: #555;
}


.line {
    border-bottom: 2px solid #000;
    margin-top: 5px;
}

/* DOCUMENT INFO */
lrft side 

.info {
     margin-top: 30px;
    line-height: 1.7;
    text-align: left;
    position: realative;


}

.info p {
    margin: 4px 0;
}

/* BODY */
.content {
    margin-top: 30px;
    line-height: 1.7;
    text-align: justify;
}

/* SIGNATURE */
.signature {
    margin-top: 60px;
    width: 100%;
}

.signature td {
    text-align: center;
}

/* FOOTER */
.footer {
    position: fixed;
    bottom: 20px;
    text-align: center;
    width: 100%;
    font-size: 12px;
}
.logo{
    width: 100px;
    height: 80px;
    padding-top:10px;

}

</style>

</head>

<body>

<!-- HEADER -->
<div class="header">

    <img src="{{ public_path('images\logo.png') }}" class="logo">

    <h5>Islamic Emirate of Afghanistan</h5>
    <H5>Ministry of Finance</h5>
    <h6>General Directorate of Budget</h6>
    <h7>Executive Management Office</h7>
    
    <!-- qr -->
     <div style="position: absolute; top: 20px; right: 20px;">
         <img src="data:image/png;base64,{{ $qr }}" width="120">
     </div>
    <div class="line"></div>
<!-- DOCUMENT INFO -->
 
<div class="info">
    <p><strong>Document No:</strong> {{ $document->document_number }}</p>
    <p><strong>Date:</strong> {{ $document->received_date }}</p>
    <p><strong>From:</strong> {{ $document->organization }}</p>
    <p><strong>Subject:</strong> {{ $document->subject }}</p>
</div>

<!-- BODY -->
 
<div class="content">
    <p>
        This document has been officially registered in the Executive Management
        Information System (EMIS) and processed according to organizational workflow.
    </p>

    <p>
        Title: {{ $document->title }}
    </p>

    <p>
        Current Status: {{ strtoupper($document->status) }}
    </p>

    <p>
        All related actions, approvals, and responses are recorded in the system
        and can be tracked for accountability and transparency.
    </p>
</div>

<!-- SIGNATURE -->
<table class="signature">
<tr>
    <td>
        Prepared By<br><br>
        ____________________
    </td>

    <td>
        Reviewed By<br><br>
        ____________________
    </td>

    <td>
        Approved By<br><br>
        ____________________
    </td>
</tr>
</table>

<!-- FOOTER -->
<div class="footer">
    Generated by EMIS System | {{ date('Y-m-d') }}
</div>

</body>
</html>

